[package]
name = "embercore-web-back"
version = "0.1.0"
authors = ["Rexagon <reide740@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4"
serde = { version = "1.0", features = ["derive"] }

[dependencies.rocket_contrib]
version = "0.4"
default-features = false
features = ["json"]
